### ISSUE TITLE
[Suggestion] Refactor NPM ports out to dedicated third party modules

### ISSUE THREAD

**Issue by asos-craigmorten** [oakserver/oak#136]
While working on my own toy Deno server project I noticed that several of the core NPM modules that make up various Node HTTP stacks (from https://github.com/pillarsjs and https://github.com/jshttp) have since been converted to their third party modules (by basically two people!!).

I don't know if the desire is maintain ports and tests of these modules in this project as a sort of monorepo, or whether there is appetite to keep the focus of Oak lean and use dedicated third parties for non "core" smarts?

Some of the modules in question that look like the easiest swap / best fit are:
- [`http-errors`](https://github.com/jshttp/http-errors) ([./httpError.ts](./httpError.ts])) --> https://github.com/ako-deno/http_errors
- [`encodeurl`](https://github.com/pillarjs/encodeurl) ([./utils.ts](./utils.ts)) --> https://github.com/ako-deno/encodeurl

(They have done [_several others_](https://github.com/ako-deno) for content negotiation, `Vary` headers etc. but aren't necessarily the best fit, or at least stray from how Oak have attacked those areas or aren't yet implemented in Oak.)

Happy to implement refactors for the two mentioned above if this matches the strategy. 😄

**Comment by kitsonk** [comment]
Personal opinion, the Node.js ecosystem is littered with single module repos and things have been broken up too much.  Those modules that are related to providing an HTTP server I would like to keep in oak and try to keep dependencies down to just `std`.

So far there are two exceptions to that, `media_types`, which is maintained here as a seperate repo only because it was moved to `std` to only have it be "ejected" and needing to take over again.  The other is `pillarjs/path-to-regexp` because it is pretty specific and complex and it is written in TypeScript with no platform specific logic.  That is the advantage of the Deno eco-system, in that we can use that discreet bit of logic without any other overhead than expressing that dependency.

Both `http_errors` and `encodeurl` are unlikely to ever change in their functionality, so I don't think maintenance is really an issue.  Some could argue why doesn't ako use the oak modules, as they existed in oak prior to ako and they don't have to be in a seperate repo to be able to pick and choose using them.

Would be glad to have a chat with @ngot and @wileam about ako and why they felt oak didn't meet their needs, especially because they are in the same time zone as myself.

**Comment by asos-craigmorten** [comment]
@kitsonk fair enough! Feel free to close 😄

**Comment by ngot** [comment]
Thanks @asos-craigmorten for recommending my ported modules to oak, I really appreciate that. Kudos to @kitsonk for creating oak for Deno developers. 

Regarding the questions, let me try to answer,

> why they felt oak didn't meet their needs

That is not the problem of oak, it is mine. When I started to explore Deno, I didn't find any Koa like framework(Forgive me, I didn't find oak at the beginning). So, I decided to write a Koa like framework for Deno. I shared that idea on Discord, people told me there was already oak there. I quickly went through oak source code, and find some interesting points:

  - It is not going to following koa's API design
  - It is not fully functional compatible with Koa

I understand the reason behind the decision, not all of Koa's pattern are suitable for Deno. Redesign and make it looks more native to Deno and TS is needed to build a new community.

So, I changed my mind to stop doing duplicated work, but only PORT a Koa compatible framework to Deno instead, even though many designs of Koa might not be the best practice in Deno, and I also want to retain the dark magic of Koa. There are several reasons: 

- I personally want a full-feature Koa like framework to migrate my personal project into Deno.
- I believe a PORTed Koa, will bring more people from the Node community to try Deno.
- Even there are many downsides in Koa, but it already proved itself in many production-level projects, if I can port it and migrate a project from Node to Deno, it will give people more confidence to adopt Deno.


> single module repos and things have been broken up too 

I agree with this. Node modules hell is a nightmare. But I still did that somehow. 

Why?

IMO, writing, or maintain a module is different from adopting a module. A high-quality module should be well documented, a good history log, and easy to find. I separate them into dedicated repos is mostly due to the SEO consideration. 

But, from an adopter perspective, [But what if the host of the URL goes down? The source won't be available.](https://deno.land/manual/linking_to_external_code#but-what-if-the-host-of-the-url-goes-down-the-source-wont-be-available) gives a great guide. Maybe, I should link that page to the document of the ported modules.

Those modules are already in oak, there is no need to link to a third-party module.

**Comment by kitsonk** [comment]
Thank you both for the conversation.

Yes, @ngot you are right, oak is inspired by Koa, not specifically trying to be a port and it certainly doesn't maintain API alignment.  Certainly the goals (and needs you have) would not be met by oak.

I think everyone here appreciates we are early in the lifecycle of Deno.  I didn't specifically create oak out of personal need, it was more a side chat with Ry and myself where I said I wanted to "experiment" with creating an HTTP middleware framework and Ry stating that Deno needed something early on in that space, a lesson he learned from the Node.js days.  I have enjoyed maintaining it and adding to it.  I don't know if it will become _the_ middleware framework for Deno, I know I personally don't need it to be, it mostly helps me understand using Deno better, a bit of dog-fooding, as well as a proving ground for ideas and patterns.

So hopefully we can all continue to learn from each other.

**Comment by asos-craigmorten** [comment]
@kitsonk right you are! And I think you've done an amazing job creating something that can enable developers to really get started with Deno - learning something new is made far easier by plenty of examples and precedent!

> mostly helps me understand using Deno better

Agreed, exactly why I started [Opine](https://github.com/asos-craigmorten/opine) despite criticism that Oak already exists and re-inventing the wheel etc. 😋  _sometimes_ you just have to build something from scratch, find it's the best way to really understand the fundamentals and standard libs of a new language/platform etc. (well for me anyway!)

Keen to start helping out here (and potentially on core) so feel free to hit my up with any issues that might be "good first issues" (I have a look through!).

Closing this for now as the original issue is a "won't do" - separate discussion can happen in another issue or [elsewhere](https://discord.com/channels/684898665143206084/684911491035430919).
