### ISSUE TITLE
Is there a production example of oak?

### ISSUE THREAD

**Issue by viztastic** [oakserver/oak#175]
It'd be great to include a lean example of how Oak could/should be configured for a production use case. Helps eliminate best-practice guesswork especially with respect to security and approaches to testing.

**Comment by asad-mlbd** [comment]
Here is my starter repo for production API with oak. Still, many things need to add or update. 
https://github.com/asad-mlbd/deno-api-starter-oak

Expecting Comments, PR, issues, thanks!

**Comment by viztastic** [comment]
Hi @asad-mlbd thanks for sharing, I took a look and posted a few questions/thoughts in your repo. I think it's a great start but there's a few (critical) bits and pieces before it can be considered a production/security-ready codebase.

But the idea of having something like this is amazing.

**Comment by asad-mlbd** [comment]
@viztastic replied
https://github.com/asad-mlbd/deno-api-starter-oak/issues/3#issuecomment-648697011

**Comment by kitsonk** [comment]
Let's keep the conversation here on topic.  Mentioning here that you commented on other issues in other repos really isn't on topic.

**Comment by GuilhermeVendramini** [comment]
Hi guys, I'm creating a small REST API and CMS using AOK:

Project: **http://denocms.net/**

Demo online: **http://demo.denocms.net/**
The demo will be slow at the first access, because I'm hosting on Heroku free account.

In the demo you can create an user, login and create contents to test the application (all content and users will be removed after a period).

This is my first experience with development using a javascript framework, so feedbacks are welcome.
