### ISSUE TITLE
Something went wrong if there's chinese char in my form-data.

### ISSUE THREAD

**Issue by warwr1ck** [oakserver/oak#211]
When I use form-data to upload files, if the file's name includes chinese, the FormDataBody will throw error Form data part missing content-disposition header. 

![image](https://user-images.githubusercontent.com/14226761/87641822-39a15280-c77b-11ea-8cb9-58275acf7040.png)

If the file's originName is without chinese char the program goes well
![image](https://user-images.githubusercontent.com/14226761/87641973-740aef80-c77b-11ea-9310-489385e93994.png)

and my deno version is 1.12.0
my oak version is 6.0.0

sorry for my pool English.

**Comment by ToWeLong** [comment]
可以看下你的路由的代码吗

**Comment by kitsonk** [comment]
I thought I was handling this properly, but obviously not.

**Comment by warwr1ck** [comment]
> 可以看下你的路由的代码吗

![image](https://user-images.githubusercontent.com/14226761/87738629-681d3d00-c810-11ea-8acf-9d52a674fe36.png)

**Comment by ToWeLong** [comment]
> > 可以看下你的路由的代码吗
> 
> ![image](https://user-images.githubusercontent.com/14226761/87738629-681d3d00-c810-11ea-8acf-9d52a674fe36.png)

你可以在response请求头中加入image/png
![image](https://user-images.githubusercontent.com/41502558/87739451-710f0e00-c812-11ea-85c9-ece4417bc549.png)

**Comment by kitsonk** [comment]
No I think the example is fine... It should be working with the filename with multi-byte-chars.  I know when I decode the filename, I was using what I thought was the industry standard for encoding such file names, but I need to look and see how something like the above is actually encoded and make sure it is decoded properly.

**Comment by warwr1ck** [comment]
> > > 可以看下你的路由的代码吗
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/14226761/87738629-681d3d00-c810-11ea-8acf-9d52a674fe36.png)
> 
> 你可以在response请求头中加入image/png
> ![image](https://user-images.githubusercontent.com/41502558/87739451-710f0e00-c812-11ea-85c9-ece4417bc549.png)

与response的请求头无关，如果上传成功，请求返回的主体不是图片，而是一串json数据。
问题出在，在接收中文名的文件时，FormDataReader中的read方法时，报错了……

**Comment by ToWeLong** [comment]
> > > > 可以看下你的路由的代码吗
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/14226761/87738629-681d3d00-c810-11ea-8acf-9d52a674fe36.png)
> > 
> > 
> > 你可以在response请求头中加入image/png
> > ![image](https://user-images.githubusercontent.com/41502558/87739451-710f0e00-c812-11ea-85c9-ece4417bc549.png)
> 
> 与response的请求头无关，如果上传成功，请求返回的主体不是图片，而是一串json数据。
> 问题出在，在接收中文名的文件时，FormDataReader中的read方法时，报错了……

你打个断点看看什么问题

**Comment by kitsonk** [comment]
这是一个有效的错误，我会修复。

**Comment by ToWeLong** [comment]
> 这是一个有效的错误，我会修复。

wow ！有心了，还用中文回复

**Comment by kitsonk** [comment]
Ok, this is a bit more complicated than I thought.  Technically, headers aren't supposed to be encoded in UTF-8.  They are supposed to be encoded in ISO-8859-1.  The problem is everyone encodes them in UTF-8 these days and people just accept it, except that the Deno implementation of `Header` is compliant with the spec, which does not allow UTF-8 encoded keys or values.  So when I iterate over the headers of the multipart header, it tries to add a value that is invalid, and so it throws.  For some reason I can't remember, I just swallow errors when adding headers so the error that displayed was that `Content-Disposition` was missing when in fact it was "invalid".

So it looks like for multi-part headers, I can't use the `Header` object and just need to deal with them as a `Record` type, which I will fix.

Thanks for finding the bug.
