### ISSUE TITLE
How to implement a 404 page? (question)

### ISSUE THREAD

**Issue by Danieliessen** [oakserver/oak#242]
I have been struggling to implement a 404 page in deno(oak server framework) - if i load any addtress that does not exist, i get just a blank page..

 [![blank page sample][1]][1]

  [1]: https://i.stack.imgur.com/Jc84U.png

**Comment by kaleidawave** [comment]
After using the router for middleware you can have a open middleware which will match on all requests

```js
app.use(router.routes());
app.use(router.allowedMethods());

app.use((ctx) => {
    ctx.response.body = "404 Route";
});
```

**Comment by Danieliessen** [comment]
Thanks!

**Comment by NfNitLoop** [comment]
Sorry for pinging an old issue, but for anyone who comes here from a Google search as I did:  

The above advice no longer seems accurate.  (Maybe oak's routing rules changed since then?) 

This is what I ended up with after reading a couple other sources (including the [docs on error handling][1]).

[1]: https://deno.land/x/oak@v11.1.0#error-handling

```typescript
const app = new Application();

// Handle 404s:
app.use(async (ctx, next) => {
    await next()

    let {status, body} = ctx.response
    if (status === 404 && body === undefined) {
        let path = ctx.request.url.pathname
        ctx.response.body = `Not found: ${path}`
    }
})
```
