### ISSUE TITLE
Property 'params' does not exist on type 'Context<Record<string, any>>'

### ISSUE THREAD

**Issue by kourosz-nsaa** [oakserver/oak#279]
I don't know how to resolve this linter error. I don't like to disable the linter. I really appreciate it.

The example code:

export const saveAnswer = async (ctx: any) => {
.
.
   let id = ctx.params.id;
.
.
}

**Comment by kourosz-nsaa** [comment]
Sorry, updated the previous code that is actually the cause of error:

export const saveAnswer = async (ctx: Context) => {
.
.
let id = ctx.params.id;
.
.
}

**Comment by LtWilhelm** [comment]
For whatever reason, Context doesn't have an optional field for params, which seems like an oversight to me. I was able to get around this by creating a union with a custom type inline like so: 
`async (ctx: Context & { params?: { id?: string } }) => {...}`
and then just checking that params.id exists before executing any code that required it.

This is so hacky and gross, I should not have to modify a library's type definition in order to have type safety. What I would like to see is Context have a type argument for the type of params, something that would look like `Context<{params: {id: string}}>` or better yet `Context<{id: string}>` both of which are common in other TS packages.

**Comment by kitsonk** [comment]
It isn't an oversight, this is what [state](https://github.com/oakserver/oak/blob/main/docs/FAQ.md#how-do-i-pass-custom-propertiesstate-around) is for.
