### ISSUE TITLE
Support `ctx.locals` for temporary state

### ISSUE THREAD

**Issue by thesmart** [oakserver/oak#283]
It's common in web frameworks to have a way to pass state down the middleware stack.  For example:

* Express has [`res.locals`](http://expressjs.com/en/api.html#res.locals)
* Opine has [`res.locals`](https://github.com/asos-craigmorten/opine/blob/main/.github/API/application.md#applocals)
* Dashport, the authentication middleware for Oak, has as monkey-patched [`ctx.locals`](https://github.com/oslabs-beta/dashport/blob/main/lib/types.ts#L19)

Furthermore, I noticed in [`class Context`](https://github.com/oakserver/oak/blob/684fdda8ec38d3c0623cc68d28a01b2650cbd6dd/context.ts#L68-L70) some dangerous documentation that `ctx.state` is `[t]he object to pass state to front-end views`.  This lead me down a rabbit hole, trying to implement user session data that leaked private information between multiple requests. This doesn't seem like a good recommendation, and luckily I caught it in test before any real user was affected.

I propose we add locals to `Context`:
```js
const app = new Application<any, { userId: number }>();
const router = new Router();
router.get("/", (context) => {
  context.locals.userId = authenticateRequest(context.request);
});
```

WDYT?

**Comment by kitsonk** [comment]
oak follows the koa model, which uses `state` versus `locals`.  It appears though that koa resets the `state` object on every request.  This means it is actually a bug that the state persists between requests.

I am going to look into it a bit more, but I am resistant into introducing `locals` as I personally find the term confusing and ambiguous.

**Comment by kitsonk** [comment]
Ok, taking a look at it, it was inconsistent with koa that `.state` was not unique per request.

What I would like to do I have committed to the v7 branch: https://github.com/oakserver/oak/commit/9a7e487ff5f82c91ba86f4b572d5e111f4ad8ea1

Where `context.state` is cloned from `app.state` when created.  This will allow people to annotate shared things across the application in `app.state` which will be available when a new context is created, but each `context.state` lives and dies with that specific context.

**Comment by kitsonk** [comment]
Ok, I have merged the v7 branch in and the commit is here: 1590ac9ee24a1be5f29e3af89e7194454c64ac74

**Comment by thesmart** [comment]
> Ok, taking a look at it, it was inconsistent with koa that `.state` was not unique per request.

I understand the tradeoff for the goal of being like Koa, but I wonder if following Koa's implementation is helpful or harmful. I have used Koa and have found it's architecture especially limiting. It's popularity is [not growing according to State of JS](https://2020.stateofjs.com/en-US/technologies/back-end-frameworks/) survey, with more developers stating that they are not interested in using it over time.

> each context.state lives and dies with that specific context.

I don't love this solution b/c it limits `state` in a few important ways.  It limits`state` to only cloneable data types, meaning that things like connections to a DB can't be shared between middleware.  This is a significant limitation to authors of middleware that may want to, for example, provide connection handling tied to an `Application` instance.  The change makes it so that middleware can't mutate `context` for other middleware. Now an author needs to figure out some kind of of global `Map` or `Application` factory closure in order to use state w/ particular `Application` instances.  This seems like an unnecessary limitation for publishers of Oak middleware modules who may want to share common interfaces.

**Comment by eric-burel** [comment]
Hi, I landed here because the current doc for context state is not totally clear about the scope. `ctx.state` is initialized with app state (so that you get global stuff like a db connection) but scoped to the request, so that you can enhance it?

Example use case I have: I have a PUT and a DELETE route for Foos, and I rely on the "fooId" route param.

```ts
  .put("/:fooId", checkAuth, async (ctx) => {
    const fooId = ctx.params["fooId"];
    const foo = await readFoo(fooId);
    if (!foo) {
      ctx.response.status = 404;
      return;
    }
    await updateFoo(foo)
```
I want to reuse the top part, that tries to get the "foo", and immediately 404 if its not found. Which means creating a middleware that stores the "foo" somewhere in the context, for downstream middlewares to consume it (delete the foo, update the foo, check ownership, whatever).

Maybe I've missed the point of middlewares or I don't separate concerns correctly, but I've found this basic use case quite difficult to sort out in other frameworks. You either have a very verbose code where you repeat the check and response logic like I've shown, or totally separate middlewares that passes value via context, but it's often not very documented and quite hard to type.
