### ISSUE TITLE
Response body errors with null

### ISSUE THREAD

**Issue by andreespirela** [oakserver/oak#309]
If a route returns `null` or `undefined`, it behaves like if there was no endpoint for that route and throws this error:
![image](https://user-images.githubusercontent.com/60560109/117006607-a78d1b00-acb6-11eb-8356-a31d219badc6.png)

![image](https://user-images.githubusercontent.com/60560109/117006634-ad82fc00-acb6-11eb-9283-11e1912d3c17.png)

. This should not be happening, `null` or `undefined` does not remove the fact that the route exists, behavior should be displaying an empty page (I believe this was the behavior in old versions of oak). 
- `null` or `undefined` does not mean the request did not succeed, it may very well succeeded and not display anything

### Code to reproduce

```typescript

import { Application } from "https://deno.land/x/oak/mod.ts";

const app = new Application();

// Logger
app.use(async (ctx, next) => {
  await next();
  const rt = ctx.response.headers.get("X-Response-Time");
  console.log(`${ctx.request.method} ${ctx.request.url} - ${rt}`);
});

// Timing
app.use(async (ctx, next) => {
  const start = Date.now();
  await next();
  const ms = Date.now() - start;
  ctx.response.headers.set("X-Response-Time", `${ms}ms`);
});

// Hello World!
app.use((ctx) => {
  ctx.response.body = null;
});

await app.listen({ port: 8000 });
```

**Comment by kitsonk** [comment]
It was "intentional" actually, in that if there was no body and the `response.status` hand't been set, we were defaulting to `404 Not Found` which is desirable if no body is set, but if the body has been explicitly set to `null` or `undefined` then `404 Not Found` is not desirable.

The fix in af21480 will set the status to `204 No Content` if the body is explicitly set to `null` or `undefined` if `response.status` has not been explicitly set, but will continue to return `404 Not Found` if neither the status or the body have been explicitly set by the middleware.
