### ISSUE TITLE
SSE Server should have an option to "poll" the connection to detect disconnection and keep-alive

### ISSUE THREAD

**Issue by al6x** [oakserver/oak#326]
In the example below the `close` event is never fired, even if the browser page is closed, neither immediately nor if waited for some time.

```TypeScript
import { Application, Router } from "https://deno.land/x/oak/mod.ts";

const app = new Application();
const router = new Router();

router.get("/pubsub", (ctx) => {
  const headers = new Headers([["Access-Control-Allow-Origin", "*"]]);
  const target = ctx.sendEvents({ headers });
  target.addEventListener("close", (evt) => {
    console.log("closed")
  });
});

app.use(router.routes());
await app.listen({ port: 5000 });
```

**Comment by kitsonk** [comment]
What version of Deno are you using and what `deno` command line arguments did you use to run this example?

**Comment by al6x** [comment]
```
deno --version
deno 1.10.3 (release, x86_64-apple-darwin)
v8 9.1.269.27
typescript 4.2.2
```

```
deno run --allow-net play.ts
```

**Comment by kitsonk** [comment]
The problem here is that we don't poll the connection, we only check that we are still connected when an event is sent.  If the event is sent and fails to be able to written to the connection, then the close event is fired.  If you were to modify your code to be something like this:

```ts
import {
  Application,
  Router,
  ServerSentEvent,
} from "https://deno.land/x/oak/mod.ts";

const app = new Application();
const router = new Router();

router.get("/pubsub", (ctx) => {
  const headers = new Headers([["Access-Control-Allow-Origin", "*"]]);
  const target = ctx.sendEvents({ headers });
  const id = setInterval(() => {
    const evt = new ServerSentEvent(
      "message",
      { hello: "world" },
    );
    target.dispatchEvent(evt);
  }, 2000);
  target.addEventListener("close", (evt) => {
    console.log("closed");
    clearInterval(id);
  });
});

app.use(router.routes());
await app.listen({ port: 5000 });
```

You would notice that the event if fired.  The `Deno.Conn` does not provide any "events" that indicate when the connection closes except to try to write to it.

On the other hand, "polling" the connection to keep it alive as well as "proactively" detect closure should be an option ([as mentioned on MDN](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#event_stream_format)).  So I have changed this to a feature request.

**Comment by al6x** [comment]
I suspected something like that. I'm currently pinging connections every 10 sec or so, to detect disconnected and free the resources.
