### ISSUE TITLE
multipart/form-data makes a file that 2 bytes longer than original.

### ISSUE THREAD

**Issue by yrm006** [oakserver/oak#335]
I'm using 
`request.body({ type: 'form-data'})`
and
`.value.read()`

But the file created has 2 bytes '\r\n' additional data, so my sent file don't work correctly.

**Comment by kitsonk** [comment]
Can you provide a more complete reproduction?

**Comment by yrm006** [comment]
I pushed a minimal sample for this issue.

https://github.com/yrm006/test.oak-formdata

thank you,

**Comment by zlumyo** [comment]
Hi there! I have investigated this issue. Looks like bug is at _multipart.ts_, `parts` function. At the end of it writing bytes to file occurs. I think it should write `strippedBytes` instead of `bytes`.

Why? Consider mutipart body of request:
```
-----------------------------315149863935715461599153835
Content-Disposition: form-data; name="test_file"; filename="10byte.txt"
Content-Type: text/plain

1234567890
-----------------------------315149863935715461599153835--
```
In `parts` function `body.readLine`-call will return bytes `['1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '\r', '\n']`. And this bytes will be written to file as is. That's why we have 2 extra bytes.

**Comment by kitsonk** [comment]
I'll try to fix it later today.

**Comment by yrm006** [comment]
thank you!
