### ISSUE TITLE
setting `response.body` changes `response.status`

### ISSUE THREAD

**Issue by jimmont** [oakserver/oak#448]
When handling responses to provide a body for errors, like catching a 404, setting the response.body also changes the status to 200.

Any changes to the status are unexpected--ie I'm not expecting changes to the status.

```
oak@v10.1.0
deno 1.17.2 (release, aarch64-apple-darwin)
```

If I simply need to read the docs and adjust expectations please call it out. Thanks.

Generalized:
```js
app.use(async ({response, request}, next) => {
	try{
		await next();
	}catch(err){
		console.warn(`status before: ${ response.status }`);
		response.body = `<!doctype html>
<html><body>
<p>${ response.status } (error status shown in page, eg 404, before it's changed to 200)</p>
</body></html>`;
		console.warn(`status after: ${ response.status }`);
	}
});
```

**Comment by kitsonk** [comment]
When `response.status` is not explicitly set, it is inferred from the context.  [`ctx.reponse.status` inline documentation](https://doc.deno.land/https://deno.land/x/oak@v10.1.0/mod.ts/~/Response#status) discuss it in part.  Simply explicitly setting the status should resolve any issues, instead of it being inferred.
