### ISSUE TITLE
How to access the native Request from context?

### ISSUE THREAD

**Issue by jsejcksn** [oakserver/oak#501]
This is about accessing a JS native [`Request`](https://developer.mozilla.org/en-US/docs/Web/API/Request) instance.

---

Between versions [`10.2.1` and `10.3.0`](https://github.com/oakserver/oak/compare/v10.2.1...v10.3.0#diff-ac2c89c169fc30ecc5e48c5b830c4c2b67fc5976671d9ebe66bf6c8579687367), the type of `context.request.originalRequest` changed [from](https://github.com/oakserver/oak/blob/v10.2.1/request.ts#L86) [`NativeRequest`](https://github.com/oakserver/oak/blob/v10.2.1/http_server_native.ts#L61) [to](https://github.com/oakserver/oak/blob/v10.3.0/request.ts#L85) [`ServerRequest`](https://github.com/oakserver/oak/blob/v10.3.0/types.d.ts#L82).

[`NativeRequest`](https://doc.deno.land/https://deno.land/x/oak@v10.2.1/http_server_native.ts/~/NativeRequest) had a getter property `request` which provided access to the native [`Request`](https://developer.mozilla.org/en-US/docs/Web/API/Request) object. In juxtaposition, [`ServerRequest`](https://doc.deno.land/https://deno.land/x/oak@v10.3.0/types.d.ts/~/ServerRequest) does not have any such property.

This has broken a tool I used which [`clone`](https://developer.mozilla.org/en-US/docs/Web/API/Request/clone)d the JS native `Request` in order to get a copy (and further use its native properties and methods). In the latest versions of oak, how can I access (or create) a JS native [`Request`](https://developer.mozilla.org/en-US/docs/Web/API/Request) instance from a given context?

**Comment by kitsonk** [comment]
The problems with unexpected coupling.  It is still a `NativeRequest` and [`NativeRequest.request`](https://doc.deno.land/https://deno.land/x/oak@v10.5.0/mod.ts/~/NativeRequest#request) still exists.  The problem was that oak originally only supported the `std` HTTP request, then supported the Deno native request, and then the legacy `std` was dropped.  This meant `originalRequest` was then only ever `NativeRequest` (it used to be a union of std and native).

So when support for Node.js was added, a new interface was created, `ServerRequest` that codified the request abstractions into a single interface, and then `originalRequest` became that type.

A quick workaround to simply case `originalRequest` as `NativeRequest` (or cast as any and call the `.request` property any.

The `mod.ts` only exports the type `NativeRequest` and I would want to keep it that way.  It really isn't public, but I can see why people might want to get to the underlying request.  The best long term, most type safe solution would be to provide a `isNativeRequest(ctx.request.originalRequest)` type guard that would allow the type to be narrowed to `NativeRequest` and provide type safe access to it.
