### ISSUE TITLE
Remove some private field modifiers from Router

### ISSUE THREAD

**Issue by denizdogan** [oakserver/oak#597]
It is very hard to subclass Router with all of its private field `#` modifiers. I think it should be simpler.

Removing the private field modifier (`#`) from `#useVerb` would go a long way. I would suggest also removing `#` from `#register`. Or at the very least make them `protected` to permit access by subclasses.

(Maybe a bit related: #278)

**Comment by kitsonk** [comment]
What is the use case of subclassing router, and why does access to private methods make it difficult?

**Comment by denizdogan** [comment]
@kitsonk So `Router` has lots of awesome functionality, which I'm sure wasn't trivial to implement. Subclassing the router could have all sorts of use cases, for example in order to programmatically configure the router given a formal API specification. As far as I've been able to tell, it's impossible to call `#register` or `#useVerbs` from the outside, so to speak.

Is there any particular reason why these methods are private in the first place?

**Comment by kitsonk** [comment]
Because they don't make part of the public API of the router.

The oak router is not meant to be derivable. If it is missing features, those would stand on its own merits for consideration. The current abstraction that I want to maintain as part of the project, and would consider exposing non-public methods as not a desire of the project. Therefore, respectfully declined.
