### ISSUE TITLE
"connection closed before message completed" when closing SSE response

### ISSUE THREAD

**Issue by r-ae-i** [oakserver/oak#602]
When connection to Server-Sent Events is closed, following error is thrown:

```
SSE disconnect 127.0.0.1
[uncaught application error]: Http - connection closed before message completed

    at Object.respondWith (ext:deno_http/01_http.js:331:25)
    at eventLoopTick (ext:core/01_core.js:173:13)
[uncaught application error]: Http - connection closed before message completed
```

Reproduce with this [SSE server example][0]. Run `curl http://127.0.0.1:8000/sse` in terminal and after second or two press `C-c` to abort the connection.

I'd expect SSE disconnects would be handled silently, without throwing an uncaught error. Is it possible to somehow handle this case to avoid logging?

There is a similar issue https://github.com/oakserver/oak/issues/387 but it targets logging itself, not a problem of uncaught error.

[0]: https://github.com/oakserver/oak/blob/e3aff80041720a41343d2d31f970f6b1d09700c7/examples/sseServer.ts
[1]: https://github.com/oakserver/oak/issues/387

**Comment by kitsonk** [comment]
This is working as designed. SSE disconnects are handled silently, if there isn't potentially something that, like an event that didn't make it to the client, which is the case here.  Because of that, an error is thrown, which may be meaningful in some situations, for example if the unsent message required some updating of state on the server side, because it didn't actually make it to the client.

The [FAQs](https://oakserver.github.io/oak/FAQ#i-am-seeing-uncaught-application-error-in-the-output-what-is-going-on) discuss this and how to disable the logging if not desired.
