### ISSUE TITLE
⚡ params field missing from Context type

### ISSUE THREAD

**Issue by eratio08** [oakserver/oak#66]
The `params` field seems to be missing from the `Context` type.
See https://doc.deno.land/https/deno.land/x/oak/mod.ts#Context

Currently working around this by:
```typescript
router.get("/:name",  (
    ctx: oak.Context & {params: { name: string } }
) => {...});
```

**Comment by kitsonk** [comment]
@eratio08 `params` exists only on the `RouterContext`, which is what is passed to router middleware.  The type is inferred be default, so there should be no need to type the `ctx`.  The following works fine:

```ts
router.get("/:name", (ctx) => {
  ctx.params; // no error
});
```

If you want to strongly type the context, there is a generic you can supply:

```ts
router.get<{ name: string }>((ctx) => {
  ctx.router.name;  // again, no error
});
```

If for some reason you want to be explicit about the type on a router context, use `RouterContext` instead of `Context` as it is also exported from the `mod.ts`.

**Comment by mkkhedawat** [comment]
Just curious, Why would we restrict anybody to be able to use params object in any other subsequent function outside router? @kitsonk

**Comment by kitsonk** [comment]
😕 The params directly relate to the route that was parsed.  Subsequent functions outside of the router wouldn't be for that route.

**Comment by mkkhedawat** [comment]
Pardon me, I misread the `RouterContext`.
