### ISSUE TITLE
Q&A: Can you close the server manually? 

### ISSUE THREAD

**Issue by olaven** [oakserver/oak#68]
Thanks for maintaining this project!

I want to close down the Oak server each test.
```typescript 
application.use(...routes);
application.listen({ port });
test_code(port); 
application.close(); // <-- Something like this 
```

Is this possible? 

Olav

**Comment by kitsonk** [comment]
It doesn't exist at the moment, but it makes sense.

**Comment by kitsonk** [comment]
Fixed in 3e7048e4b8b3b4ae7212e5844792feab5056d450 but take a look at the changes.  Sorry I didn't make it clear I had a plan for it.

**Comment by adoi** [comment]
@kitsonk What would happen to servers that don't have a `signal`? Why not provide a `server.close()` method that would make oak compatible to libraries that have to close servers often?

**Comment by kitsonk** [comment]
@adoi abort signals are the browser standard for aborting asynchronous processes, I would prefer to align to that.  From an overall architecture perspective, I am not convinced that the ability to close the server and stop processing requests should be an implicit API offered up to middleware.  The ability to allow middleware to do that should be explicit.  For example is someone wanted to create a middleware library that needed to close the server, the would have a constructor (or factory) that would take the abort controller as an argument.  This would ensure that the consumer of the middleware is explicit of allowing the middleware to potentially close the server:

```ts
import { Application } from "https://deno.land/x/oak/mod.ts";
import { SomeMiddleware } from "https://some.lib/mod.ts";

const abortController = new AbortController();
const { signal } = abortController;
const app = new App({ signal });
const app.use(new SomeMiddleware({ abortController }));
app.listen();
```

Is there an example of a library otherwise compatible with oak that is simply missing a server `close()`?

oak doesn't aim to be compatible with middleware that wasn't written for it.  It is fully embracing Deno and Deno's patterns as well as trying to cut down on the _n_ number of ways to do something that I feel is a challenge with koa and koa-router.
