### ISSUE TITLE
Request body middleware

### ISSUE THREAD

**Issue by bartlomieju** [oakserver/oak#7]
I wanted to make simple REST API with oak but noticed that there is no `body` field on `Request`, or worse any way to access underlying `ServerRequest`'s body. I guess body parsing middleware is missing.

**Comment by kitsonk** [comment]
HA! Yeah, good point.  🤦‍♂️

**Comment by bartlomieju** [comment]
We'll need to implement [Koa's request.is](https://koajs.com/#request) method to be able to negotiate content.

**Comment by kitsonk** [comment]
Closed in 81326b2a1aa292cd1de837841fcb6b6bdfbf4c73

I took a little bit different direction.  Instead of a seperate middleware, `context.request.body()` returns a `Promise` that will resolve with a parsed body for JSON, URL encoded forms, or text.  So basic use cases should _just work_.

I would like to automagically deal with multi-part forms, but that might be best with seperate middleware, versus baking that into the response.  The original `net` server request is also available publically now which provides the `body()` and `bodyStream()` for more advanced use cases.

**Comment by bartlomieju** [comment]
Awesome, thanks for that @kitsonk I'll put up example REST project with oak and postgres.

**Comment by chovy** [comment]
This doesn't work for native forms

**Comment by kitsonk** [comment]
That API has been significantly update since this issue was closed.  What about the [current API](https://github.com/oakserver/oak#request) doesn't work?
